# Generated by Django 4.2.4 on 2023-11-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars')),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
