version: '3'
services:
  web:
    build: .
    command: /bin/bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: mini_twitter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 111
    ports:
      - "5432:5432"